### ISSUE TITLE
adding package fails

### ISSUE THREAD

**Issue by akagh** [martinhodler/unity-aseprite-importer#44] opened 2021-01-15 01:30 UTC
Upon adding the package git URL in the package manager on a brand new project (and fresh Unity install), it appears to fail to import, as the package itself is empty. 

Here is the error message and the inspector on the package. It's still visible in my packages for the project, it just doesn't do anything.

![image](https://user-images.githubusercontent.com/76902112/104668944-f4100480-568d-11eb-8a48-d18d416eaea2.png)

![image](https://user-images.githubusercontent.com/76902112/104668977-05f1a780-568e-11eb-9f8c-e157ade7f1d1.png)

**Comment by martinhodler** [comment] 2021-01-15 18:34
Hi @akagh which version of Unity are you using?

**Comment by martinhodler** [comment] 2021-01-15 18:39
I was able to reproduce the error. I'm working on it.

**Comment by martinhodler** [comment] 2021-01-15 18:51
This looks like a weird issue... The file on github doesn't look like the one i cloned. Like the unity packagemanager is cloning the file in a wrong way...

**Comment by martinhodler** [comment] 2021-01-15 19:00
The issue was fixed with the commit 1deda9908735d1dc59c8e17d12bac2796f8d69cc.
It seems like the git implementation of Unity has its flaws.

**Closed by martinhodler** 2021-01-15 19:00 UTC
