### ISSUE TITLE
Renders Incomplete Spritesheet/TileMap (Pink)

### ISSUE THREAD

**Issue by advra** [martinhodler/unity-aseprite-importer#14] opened 2019-10-14 03:06 UTC
**Describe the bug**
When I try to import an aseprite file the auto-generated tilesheet from the import produces an incomplete output. (See screenshot below)

**To Reproduce**
1. Import unity-aseprite-importer into my project
2. Drag and Drop Aseprite into project
3. Let editor generate

**Expected behavior**
The spritesheet should have all 7 frames properly rendered; however, only the first frame is showing. The rest shows up as pink.

**Screenshots**
![image](https://user-images.githubusercontent.com/1753803/66727556-ea498280-edf4-11e9-98dc-9c44ca7ec687.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: Unity 2018.2.4.f1

**Comment by martinhodler** [comment] 2019-10-16 17:18
Did you get the same issue with other files? It looks like there is an error in the image composing instead of the tilemap generation. Both (sprite import and tileset import) do use the same sprite-atlas generator... so there shouldn't be any difference. Can you send me a file which reproduces this error?

**Comment by advra** [comment] 2019-10-17 03:15
It looks like all my other pixel games have been affected. I had another project from 8 months ago breaking all of a sudden, which is quite odd. 

Anyways attached is the file from the screenshot above which should reproduce the results discussed. Let me know if you need anything else.

[lava_back_ase.zip](https://github.com/martinhodler/unity-aseprite-importer/files/3737265/lava_back_ase.zip)

**Comment by martinhodler** [comment] 2019-11-04 19:11
ok I was able to reproduce the issue... just wanted you to know that I'm still working on it.

**Comment by advra** [comment] 2019-11-07 01:45
Thanks for looking into it. Do you know what is causing the issue? Ill try to help wherever I can.

**Comment by martinhodler** [comment] 2020-01-20 11:39
fixed in commit 918619d11b307eefbff1faadd9377da82c78f11e

**Closed by martinhodler** 2020-01-20 11:39 UTC

**Comment by martinhodler** [comment] 2020-01-20 11:41
The issue was that aseprite is storing the indexed-palette in the first frame only. In my implementation it searched for a palette entry in the current frame and not in the whole file.
