### ISSUE TITLE
Linked frames are imported as blank sprites

### ISSUE THREAD

**Issue by B-Reif** [martinhodler/unity-aseprite-importer#10] opened 2019-05-09 22:19 UTC
**Bug**
When importing an animation with linked frames, the link's frames after the 1st instance are imported as blank sprites. In other words, for any set of linked frames, the artwork is only present in the first frame of the set.

**To Reproduce**
1. In Aseprite, create an animation with linked frames.
2. Save the file as .aseprite and import it to Unity with the package present.
3. Examine the generated sprites and animation. Linked frames after the 1st are blank.

**Expected behavior**
I expect all linked frames in the generated animation to display the same artwork as they do in Aseprite. I also expect to see the animation re-use the same sprite asset for a set of linked frames, instead of generating a duplicate asset for each frame.

**Screenshots**
<img width="172" alt="Screen Shot 2019-05-09 at 3 18 39 PM" src="https://user-images.githubusercontent.com/12357846/57490334-c1352c80-726d-11e9-8917-82f1736fe9be.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 2019.1

**Comment by martinhodler** [comment] 2019-05-19 14:04
Which version of the importer are you using? I tried to reproduce the bug with the latest version. 

At the moment linked frames will refer the same data from the aseprite file but will generate multiple sprites. The reason for that is that multiple layers would be merged to one image and some of them could contain a linked cel in it but are with all layers a unique image. I'll try to find a better, more performant solution to this.

**Comment by B-Reif** [comment] 2019-05-20 19:01
Ah yeah, I didn't consider that the frames might not be fully linked.

I'm using version 1.0.0 of the importer.

**Comment by martinhodler** [comment] 2019-06-25 18:29
Can you send me a file which reproduces this error? I tried to create such a file with the latest version of the importer but wasn't able to reproduce it.

**Closed** 2020-01-20 11:58 UTC
Labels: bug
